
project_id = "kdmtlpyktqpemgfekxgi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://kdmtlpyktqpemgfekxgi.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.generate-roadmap]
verify_jwt = true

[functions.generate-roadmap-openai]
verify_jwt = true

[functions.intelligent-recommendations]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.enhanced-recommendations]
verify_jwt = true

[functions.ai-chat-assistant]
verify_jwt = true

[functions.real-time-tool-data]
verify_jwt = true

[functions.analytics-tracker]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.send-alert-email]
verify_jwt = true

[functions.purchase-template]
verify_jwt = true

[edge-runtime]
policy = "per_worker"
inspector_port = 8083
